from PyQt5 import QtCore, QtGui, QtWidgets
from threading import Thread
import time
import rpiTransm as rpi
import datetime
import time
import collections

koef = 1
blinkvar = 0
temperatures = collections.defaultdict(lambda: collections.deque((), 5))

def exitor():
    if exit != 1:
        print('exiting')
        sys.exit(exit)


def check_if_temperature_not_changed(t, current):
    print(t)
    if len(t) == t.maxlen and len(set(t)) == 1:
        return '-1'
    return current

def blink():
    transm.setLED(255, 255, 255)
    time.sleep(0.5)
    transm.setLED(0, 0, 0)
    time.sleep(0.5)
    if blinkvar:
        blink()

def getData():
    global blinkvar
    #energy = transm.getEnergy()
    #energy = str((float(transm.getSensor(2)) - float(transm.getSensor(1))) * 100)
    #if energy != -1:
    #    ui.energyLcd.display(energy)
    #time.sleep(0.1)
    exitor()
    messages = {}
    global temperatures
    #for num in range(1, 17):
    for num in range(1, 17):
        #val = str(transm.getSensor(num))
        messages[num] = transm.sendMsg('T {}'.format(num))
    for num, mid in messages.items():
        val = transm.getMsg(mid)
        temperatures[num].append(val)
        val = check_if_temperature_not_changed(temperatures[num], val)

        print('T {} : {} C'.format(num, val))
        if val == "-1" or val == "-666.00" or val == "0.00":
            val = '{}. -'.format(num)
        else:
            val = "{}. {}".format(num, val)
        eval("ui.t{}.display(val)".format(num))
        #time.sleep(0.1)
        exitor()
    flow = transm.getFlow(1)[2:-5]
    if flow == "-1" or flow == "-666.00":
        flow = '-'
    ui.flow1.display(flow)
    #time.sleep(0.1)
    exitor()
    flow = transm.getFlow(2)[2:-5]
    if flow == "-1" or flow == "-666.00":
        flow = '-'
    ui.flow2.display(flow)
    #time.sleep(0.1)
    exitor()
    for num in range(1, 7):
        nasos = transm.getPipe(num)[2:-5]
        if nasos == "-1" or nasos == "-666.00":
            nasos = '-'
        else:
            try:
                nasos = str(int(nasos)/10)
            except:
                nasos = '-'
        eval('ui.lcd{}.display(nasos)'.format(num))
        #time.sleep(0.1)
        exitor()
    try:
        energy = (float(temperatures[15][-1]) - float(temperatures[16][-1])) * 82 * int(ui.flow1.value()) + (float(temperatures[13][-1]) - float(temperatures[14][-1])) * 82 * int(ui.flow2.value())
    except ValueError:
        energy = 0
    if energy > 0:
        print('{0:.2f}'.format(energy))
        ui.energyLcd.display(energy)
        if energy > 6000:
            blinkvar = 0
            transm.setLED(255, 0, 0)
        elif energy > 4500:
            blinkvar = 0
            transm.setLED(255, 140, 0)
        elif energy > 3000:
            blinkvar = 0
            transm.setLED(255, 255, 0)
        elif energy > 1600:
            blinkvar = 0
            transm.setLED(0, 255, 0)
        elif energy > 900:
            blinkvar = 0
            transm.setLED(0, 0, 255)
        elif energy > 300:
            blinkvar = 0
            transm.setLED(0, 0, 128)
        else:
            blinkvar = 1
            blinkThread = Thread(target=blink, args=())
    logger()
    if exit == 1:
        getData()
    else:
        print("Exiting")
        sys.exit(exit)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Desktop/Code/Hurricane_in_glass/controls/design/Hurricane_in_glass/controls/design/img/nuke logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-image: url(:/img/img/bg_grey.jpg);")
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.menu2 = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.menu2.setFont(font)
        self.menu2.setAutoFillBackground(False)
        self.menu2.setObjectName("menu2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.reactor1Temp_2 = QtWidgets.QWidget(self.menu2)
        font = QtGui.QFont()
        font.setItalic(False)
        self.reactor1Temp_2.setFont(font)
        self.reactor1Temp_2.setStyleSheet("border: 2px solid white;")
        self.reactor1Temp_2.setObjectName("reactor1Temp_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.reactor1Temp_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.t13 = QtWidgets.QLCDNumber(self.reactor1Temp_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.t13.setFont(font)
        self.t13.setAutoFillBackground(False)
        self.t13.setStyleSheet("color: rgb(255, 255, 255);")
        self.t13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.t13.setObjectName("t13")
        self.verticalLayout_10.addWidget(self.t13)
        self.label_8 = QtWidgets.QLabel(self.reactor1Temp_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255); border: 0;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.verticalLayout.addWidget(self.reactor1Temp_2)
        self.reactor1Temp_4 = QtWidgets.QWidget(self.menu2)
        font = QtGui.QFont()
        font.setItalic(False)
        self.reactor1Temp_4.setFont(font)
        self.reactor1Temp_4.setStyleSheet("border: 2px solid white;")
        self.reactor1Temp_4.setObjectName("reactor1Temp_4")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.reactor1Temp_4)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.t14 = QtWidgets.QLCDNumber(self.reactor1Temp_4)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.t14.setFont(font)
        self.t14.setAutoFillBackground(False)
        self.t14.setStyleSheet("color: rgb(255, 255, 255);")
        self.t14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.t14.setObjectName("t14")
        self.verticalLayout_24.addWidget(self.t14)
        self.label_11 = QtWidgets.QLabel(self.reactor1Temp_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255); border: 0;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_24.addWidget(self.label_11)
        self.verticalLayout.addWidget(self.reactor1Temp_4)
        self.reactor1Temp_5 = QtWidgets.QWidget(self.menu2)
        font = QtGui.QFont()
        font.setItalic(False)
        self.reactor1Temp_5.setFont(font)
        self.reactor1Temp_5.setStyleSheet("border: 2px solid white;")
        self.reactor1Temp_5.setObjectName("reactor1Temp_5")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.reactor1Temp_5)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.t11 = QtWidgets.QLCDNumber(self.reactor1Temp_5)
        self.t11.setStyleSheet("border: 2px solid white; color: white;")
        self.t11.setDigitCount(5)
        self.t11.setObjectName("t11")
        self.verticalLayout_31.addWidget(self.t11)
        self.label_17 = QtWidgets.QLabel(self.reactor1Temp_5)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_17.setFont(font)
        self.label_17.setAutoFillBackground(False)
        self.label_17.setStyleSheet("color: rgb(255, 255, 255); border: 0;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_31.addWidget(self.label_17)
        self.verticalLayout.addWidget(self.reactor1Temp_5)
        self.reactor1Temp = QtWidgets.QWidget(self.menu2)
        font = QtGui.QFont()
        font.setItalic(False)
        self.reactor1Temp.setFont(font)
        self.reactor1Temp.setStyleSheet("border: 2px solid white;")
        self.reactor1Temp.setObjectName("reactor1Temp")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.reactor1Temp)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.t15 = QtWidgets.QLCDNumber(self.reactor1Temp)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.t15.setFont(font)
        self.t15.setAutoFillBackground(False)
        self.t15.setStyleSheet("color: rgb(255, 255, 255);")
        self.t15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.t15.setObjectName("t15")
        self.verticalLayout_9.addWidget(self.t15)
        self.label_7 = QtWidgets.QLabel(self.reactor1Temp)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_7.setFont(font)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255); border: 0;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.verticalLayout.addWidget(self.reactor1Temp)
        self.reactor1Temp_3 = QtWidgets.QWidget(self.menu2)
        font = QtGui.QFont()
        font.setItalic(False)
        self.reactor1Temp_3.setFont(font)
        self.reactor1Temp_3.setStyleSheet("border: 2px solid white;")
        self.reactor1Temp_3.setObjectName("reactor1Temp_3")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.reactor1Temp_3)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.t16 = QtWidgets.QLCDNumber(self.reactor1Temp_3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.t16.setFont(font)
        self.t16.setAutoFillBackground(False)
        self.t16.setStyleSheet("color: rgb(255, 255, 255);")
        self.t16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.t16.setObjectName("t16")
        self.verticalLayout_23.addWidget(self.t16)
        self.label_10 = QtWidgets.QLabel(self.reactor1Temp_3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255); border: 0;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_23.addWidget(self.label_10)
        self.verticalLayout.addWidget(self.reactor1Temp_3)
        self.reactor1Temp_6 = QtWidgets.QWidget(self.menu2)
        font = QtGui.QFont()
        font.setItalic(False)
        self.reactor1Temp_6.setFont(font)
        self.reactor1Temp_6.setStyleSheet("border: 2px solid white;")
        self.reactor1Temp_6.setObjectName("reactor1Temp_6")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.reactor1Temp_6)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.t12 = QtWidgets.QLCDNumber(self.reactor1Temp_6)
        self.t12.setStyleSheet("border: 2px solid white; color: white;")
        self.t12.setSmallDecimalPoint(False)
        self.t12.setDigitCount(5)
        self.t12.setObjectName("t12")
        self.verticalLayout_32.addWidget(self.t12)
        self.label_16 = QtWidgets.QLabel(self.reactor1Temp_6)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_16.setFont(font)
        self.label_16.setAutoFillBackground(False)
        self.label_16.setStyleSheet("color: rgb(255, 255, 255); border: 0;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.label_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_32.addWidget(self.label_16)
        self.verticalLayout.addWidget(self.reactor1Temp_6)
        self.widget_3 = QtWidgets.QWidget(self.menu2)
        self.widget_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.widget_3.setFont(font)
        self.widget_3.setAutoFillBackground(False)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.turnOn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setItalic(False)
        self.turnOn.setFont(font)
        self.turnOn.setStyleSheet("color:white;")
        self.turnOn.setObjectName("turnOn")
        self.verticalLayout_7.addWidget(self.turnOn)
        self.crash1 = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setItalic(False)
        self.crash1.setFont(font)
        self.crash1.setAutoFillBackground(False)
        self.crash1.setStyleSheet("color: rgb(255, 255, 255);")
        self.crash1.setObjectName("crash1")
        self.verticalLayout_7.addWidget(self.crash1)
        self.dump = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setItalic(False)
        self.dump.setFont(font)
        self.dump.setAutoFillBackground(False)
        self.dump.setStyleSheet("color: rgb(255, 255, 255);")
        self.dump.setObjectName("dump")
        self.verticalLayout_7.addWidget(self.dump)
        self.cooling = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setItalic(False)
        self.cooling.setFont(font)
        self.cooling.setAutoFillBackground(False)
        self.cooling.setStyleSheet("color: rgb(255, 255, 255);")
        self.cooling.setObjectName("cooling")
        self.verticalLayout_7.addWidget(self.cooling)
        self.modelOff = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setItalic(False)
        self.modelOff.setFont(font)
        self.modelOff.setAutoFillBackground(False)
        self.modelOff.setStyleSheet("color: rgb(255, 255, 255);")
        self.modelOff.setObjectName("modelOff")
        self.verticalLayout_7.addWidget(self.modelOff)
        self.endGame = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(16)
        font.setItalic(False)
        self.endGame.setFont(font)
        self.endGame.setAutoFillBackground(False)
        self.endGame.setStyleSheet("color: rgb(255, 255, 255);")
        self.endGame.setObjectName("endGame")
        self.verticalLayout_7.addWidget(self.endGame)
        self.modelOff.raise_()
        self.endGame.raise_()
        self.crash1.raise_()
        self.dump.raise_()
        self.cooling.raise_()
        self.turnOn.raise_()
        self.verticalLayout.addWidget(self.widget_3)
        self.horizontalLayout_4.addWidget(self.menu2)
        self.sensors = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setItalic(False)
        self.sensors.setFont(font)
        self.sensors.setStyleSheet("border: 2px solid white;")
        self.sensors.setObjectName("sensors")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.sensors)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.w = QtWidgets.QWidget(self.sensors)
        font = QtGui.QFont()
        font.setItalic(False)
        self.w.setFont(font)
        self.w.setStyleSheet("border: 0;")
        self.w.setObjectName("w")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.w)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.label = QtWidgets.QLabel(self.w)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.verticalLayout_28.addWidget(self.label)
        self.verticalLayout_27.addWidget(self.w)
        self.s1 = QtWidgets.QWidget(self.sensors)
        font = QtGui.QFont()
        font.setItalic(False)
        self.s1.setFont(font)
        self.s1.setStyleSheet("border: 0;")
        self.s1.setObjectName("s1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.s1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.t1 = QtWidgets.QLCDNumber(self.s1)
        self.t1.setStyleSheet("border: 2px solid white; color: white;")
        self.t1.setDigitCount(10)
        self.t1.setObjectName("t1")
        self.verticalLayout_6.addWidget(self.t1)
        self.verticalLayout_27.addWidget(self.s1)
        self.s1_10 = QtWidgets.QWidget(self.sensors)
        font = QtGui.QFont()
        font.setItalic(False)
        self.s1_10.setFont(font)
        self.s1_10.setStyleSheet("border: 0;")
        self.s1_10.setObjectName("s1_10")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.s1_10)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.t2 = QtWidgets.QLCDNumber(self.s1_10)
        self.t2.setStyleSheet("border: 2px solid white; color: white;")
        self.t2.setDigitCount(10)
        self.t2.setObjectName("t2")
        self.verticalLayout_20.addWidget(self.t2)
        self.verticalLayout_27.addWidget(self.s1_10)
        self.s1_9 = QtWidgets.QWidget(self.sensors)
        font = QtGui.QFont()
        font.setItalic(False)
        self.s1_9.setFont(font)
        self.s1_9.setStyleSheet("border: 0;")
        self.s1_9.setObjectName("s1_9")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.s1_9)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.t3 = QtWidgets.QLCDNumber(self.s1_9)
        self.t3.setStyleSheet("border: 2px solid white; color: white;")
        self.t3.setDigitCount(10)
        self.t3.setObjectName("t3")
        self.verticalLayout_19.addWidget(self.t3)
        self.verticalLayout_27.addWidget(self.s1_9)
        self.s1_2 = QtWidgets.QWidget(self.sensors)
        font = QtGui.QFont()
        font.setItalic(False)
        self.s1_2.setFont(font)
        self.s1_2.setStyleSheet("border: 0;")
        self.s1_2.setObjectName("s1_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.s1_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.t4 = QtWidgets.QLCDNumber(self.s1_2)
        self.t4.setStyleSheet("border: 2px solid white; color: white;")
        self.t4.setDigitCount(10)
        self.t4.setObjectName("t4")
        self.verticalLayout_12.addWidget(self.t4)
        self.verticalLayout_27.addWidget(self.s1_2)
        self.s1_3 = QtWidgets.QWidget(self.sensors)
        font = QtGui.QFont()
        font.setItalic(False)
        self.s1_3.setFont(font)
        self.s1_3.setStyleSheet("border: 0;")
        self.s1_3.setObjectName("s1_3")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.s1_3)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.t5 = QtWidgets.QLCDNumber(self.s1_3)
        self.t5.setStyleSheet("border: 2px solid white; color: white;")
        self.t5.setDigitCount(10)
        self.t5.setObjectName("t5")
        self.verticalLayout_13.addWidget(self.t5)
        self.verticalLayout_27.addWidget(self.s1_3)
        self.s1_8 = QtWidgets.QWidget(self.sensors)
        font = QtGui.QFont()
        font.setItalic(False)
        self.s1_8.setFont(font)
        self.s1_8.setStyleSheet("border: 0;")
        self.s1_8.setObjectName("s1_8")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.s1_8)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.t6 = QtWidgets.QLCDNumber(self.s1_8)
        self.t6.setStyleSheet("border: 2px solid white; color: white;")
        self.t6.setDigitCount(10)
        self.t6.setObjectName("t6")
        self.verticalLayout_18.addWidget(self.t6)
        self.verticalLayout_27.addWidget(self.s1_8)
        self.s1_7 = QtWidgets.QWidget(self.sensors)
        font = QtGui.QFont()
        font.setItalic(False)
        self.s1_7.setFont(font)
        self.s1_7.setStyleSheet("border: 0;")
        self.s1_7.setObjectName("s1_7")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.s1_7)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.t7 = QtWidgets.QLCDNumber(self.s1_7)
        self.t7.setStyleSheet("border: 2px solid white; color: white;")
        self.t7.setDigitCount(10)
        self.t7.setObjectName("t7")
        self.verticalLayout_17.addWidget(self.t7)
        self.verticalLayout_27.addWidget(self.s1_7)
        self.s1_6 = QtWidgets.QWidget(self.sensors)
        font = QtGui.QFont()
        font.setItalic(False)
        self.s1_6.setFont(font)
        self.s1_6.setStyleSheet("border: 0;")
        self.s1_6.setObjectName("s1_6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.s1_6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.t8 = QtWidgets.QLCDNumber(self.s1_6)
        self.t8.setStyleSheet("border: 2px solid white; color: white;")
        self.t8.setDigitCount(10)
        self.t8.setObjectName("t8")
        self.verticalLayout_16.addWidget(self.t8)
        self.verticalLayout_27.addWidget(self.s1_6)
        self.s1_5 = QtWidgets.QWidget(self.sensors)
        font = QtGui.QFont()
        font.setItalic(False)
        self.s1_5.setFont(font)
        self.s1_5.setStyleSheet("border: 0;")
        self.s1_5.setObjectName("s1_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.s1_5)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.t9 = QtWidgets.QLCDNumber(self.s1_5)
        self.t9.setStyleSheet("border: 2px solid white; color: white;")
        self.t9.setDigitCount(10)
        self.t9.setObjectName("t9")
        self.verticalLayout_15.addWidget(self.t9)
        self.verticalLayout_27.addWidget(self.s1_5)
        self.s1_4 = QtWidgets.QWidget(self.sensors)
        font = QtGui.QFont()
        font.setItalic(False)
        self.s1_4.setFont(font)
        self.s1_4.setStyleSheet("border: 0;")
        self.s1_4.setObjectName("s1_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.s1_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.t10 = QtWidgets.QLCDNumber(self.s1_4)
        self.t10.setStyleSheet("border: 2px solid white; color: white;")
        self.t10.setDigitCount(10)
        self.t10.setObjectName("t10")
        self.verticalLayout_14.addWidget(self.t10)
        self.verticalLayout_27.addWidget(self.s1_4)
        self.widget_4 = QtWidgets.QWidget(self.sensors)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.widget_4.setFont(font)
        self.widget_4.setAutoFillBackground(False)
        self.widget_4.setStyleSheet("border: 2px solid white;")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.energyLcd = QtWidgets.QLCDNumber(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.energyLcd.setFont(font)
        self.energyLcd.setAutoFillBackground(False)
        self.energyLcd.setStyleSheet("color: rgb(255, 255, 255);")
        self.energyLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.energyLcd.setObjectName("energyLcd")
        self.verticalLayout_8.addWidget(self.energyLcd)
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255); border: 0;")
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.verticalLayout_27.addWidget(self.widget_4)
        self.label_14 = QtWidgets.QLabel(self.sensors)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: white; border: 0px;")
        self.label_14.setObjectName("label_14")
        self.verticalLayout_27.addWidget(self.label_14)
        self.frame = QtWidgets.QFrame(self.sensors)
        self.frame.setMinimumSize(QtCore.QSize(314, 44))
        self.frame.setStyleSheet("border: 0px; ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.cslider = QtWidgets.QSlider(self.frame)
        self.cslider.setOrientation(QtCore.Qt.Horizontal)
        self.cslider.setObjectName("cslider")
        self.verticalLayout_21.addWidget(self.cslider)
        self.verticalLayout_27.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addWidget(self.sensors)
        self.waterpipes = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.waterpipes.setFont(font)
        self.waterpipes.setAutoFillBackground(False)
        self.waterpipes.setStyleSheet("")
        self.waterpipes.setObjectName("waterpipes")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.waterpipes)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.Nasos4_2 = QtWidgets.QWidget(self.waterpipes)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.Nasos4_2.setFont(font)
        self.Nasos4_2.setAutoFillBackground(False)
        self.Nasos4_2.setStyleSheet("border: 2px solid white;")
        self.Nasos4_2.setObjectName("Nasos4_2")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.Nasos4_2)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.lcd6 = QtWidgets.QLCDNumber(self.Nasos4_2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.lcd6.setFont(font)
        self.lcd6.setAutoFillBackground(False)
        self.lcd6.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd6.setObjectName("lcd6")
        self.verticalLayout_26.addWidget(self.lcd6)
        self.label_12 = QtWidgets.QLabel(self.Nasos4_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_26.addWidget(self.label_12)
        self.verticalLayout_30.addWidget(self.Nasos4_2)
        self.Nasos4_3 = QtWidgets.QWidget(self.waterpipes)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.Nasos4_3.setFont(font)
        self.Nasos4_3.setAutoFillBackground(False)
        self.Nasos4_3.setStyleSheet("border: 2px solid white;")
        self.Nasos4_3.setObjectName("Nasos4_3")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.Nasos4_3)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.lcd5 = QtWidgets.QLCDNumber(self.Nasos4_3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.lcd5.setFont(font)
        self.lcd5.setAutoFillBackground(False)
        self.lcd5.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd5.setObjectName("lcd5")
        self.verticalLayout_29.addWidget(self.lcd5)
        self.label_13 = QtWidgets.QLabel(self.Nasos4_3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_29.addWidget(self.label_13)
        self.verticalLayout_30.addWidget(self.Nasos4_3)
        self.Nasos4 = QtWidgets.QWidget(self.waterpipes)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.Nasos4.setFont(font)
        self.Nasos4.setAutoFillBackground(False)
        self.Nasos4.setStyleSheet("border: 2px solid white;")
        self.Nasos4.setObjectName("Nasos4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Nasos4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lcd4 = QtWidgets.QLCDNumber(self.Nasos4)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.lcd4.setFont(font)
        self.lcd4.setAutoFillBackground(False)
        self.lcd4.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd4.setObjectName("lcd4")
        self.verticalLayout_3.addWidget(self.lcd4)
        self.label_2 = QtWidgets.QLabel(self.Nasos4)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout_30.addWidget(self.Nasos4)
        self.Nasos3 = QtWidgets.QWidget(self.waterpipes)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.Nasos3.setFont(font)
        self.Nasos3.setAutoFillBackground(False)
        self.Nasos3.setStyleSheet("border: 2px solid white;")
        self.Nasos3.setObjectName("Nasos3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Nasos3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lcd3 = QtWidgets.QLCDNumber(self.Nasos3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.lcd3.setFont(font)
        self.lcd3.setAutoFillBackground(False)
        self.lcd3.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd3.setObjectName("lcd3")
        self.verticalLayout_4.addWidget(self.lcd3)
        self.label_3 = QtWidgets.QLabel(self.Nasos3)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.verticalLayout_30.addWidget(self.Nasos3)
        self.Nasos2 = QtWidgets.QWidget(self.waterpipes)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.Nasos2.setFont(font)
        self.Nasos2.setAutoFillBackground(False)
        self.Nasos2.setStyleSheet("border: 2px solid white;")
        self.Nasos2.setObjectName("Nasos2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Nasos2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lcd2 = QtWidgets.QLCDNumber(self.Nasos2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.lcd2.setFont(font)
        self.lcd2.setAutoFillBackground(False)
        self.lcd2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd2.setObjectName("lcd2")
        self.verticalLayout_5.addWidget(self.lcd2)
        self.label_4 = QtWidgets.QLabel(self.Nasos2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.verticalLayout_30.addWidget(self.Nasos2)
        self.Nasos1 = QtWidgets.QWidget(self.waterpipes)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.Nasos1.setFont(font)
        self.Nasos1.setAcceptDrops(False)
        self.Nasos1.setAutoFillBackground(False)
        self.Nasos1.setStyleSheet("border: 2px solid white;")
        self.Nasos1.setObjectName("Nasos1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Nasos1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lcd1 = QtWidgets.QLCDNumber(self.Nasos1)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.lcd1.setFont(font)
        self.lcd1.setAutoFillBackground(False)
        self.lcd1.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd1.setObjectName("lcd1")
        self.verticalLayout_2.addWidget(self.lcd1)
        self.label_1 = QtWidgets.QLabel(self.Nasos1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.label_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_1.setFont(font)
        self.label_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_1.setAutoFillBackground(False)
        self.label_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_2.addWidget(self.label_1)
        self.verticalLayout_30.addWidget(self.Nasos1)
        self.flow1wid = QtWidgets.QWidget(self.waterpipes)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.flow1wid.setFont(font)
        self.flow1wid.setAcceptDrops(False)
        self.flow1wid.setAutoFillBackground(False)
        self.flow1wid.setStyleSheet("border: 2px solid white;")
        self.flow1wid.setObjectName("flow1wid")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.flow1wid)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.flow1 = QtWidgets.QLCDNumber(self.flow1wid)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.flow1.setFont(font)
        self.flow1.setAutoFillBackground(False)
        self.flow1.setStyleSheet("color: rgb(255, 255, 255);")
        self.flow1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.flow1.setObjectName("flow1")
        self.verticalLayout_11.addWidget(self.flow1)
        self.label_5 = QtWidgets.QLabel(self.flow1wid)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.verticalLayout_30.addWidget(self.flow1wid)
        self.flow2wid = QtWidgets.QWidget(self.waterpipes)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.flow2wid.setFont(font)
        self.flow2wid.setAcceptDrops(False)
        self.flow2wid.setAutoFillBackground(False)
        self.flow2wid.setStyleSheet("border: 2px solid white;")
        self.flow2wid.setObjectName("flow2wid")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.flow2wid)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.flow2 = QtWidgets.QLCDNumber(self.flow2wid)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setItalic(False)
        self.flow2.setFont(font)
        self.flow2.setAutoFillBackground(False)
        self.flow2.setStyleSheet("color: rgb(255, 255, 255);")
        self.flow2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.flow2.setObjectName("flow2")
        self.verticalLayout_25.addWidget(self.flow2)
        self.label_9 = QtWidgets.QLabel(self.flow2wid)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.label_9.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(18)
        font.setItalic(False)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_25.addWidget(self.label_9)
        self.verticalLayout_30.addWidget(self.flow2wid)
        self.horizontalLayout_4.addWidget(self.waterpipes)
        MainWindow.setCentralWidget(self.centralwidget)

        def translucent(widget):
            widget.setWindowFlags(QtCore.Qt.FramelessWindowHint)
            widget.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        for i in range(1, 15):
            eval("translucent(self.label_{})".format(i))

        translucent(self.frame)

        self.turnOn.clicked.connect(transm.turnOn)
        self.modelOff.clicked.connect(transm.turnOff)
        self.crash1.clicked.connect(transm.testAlarm)
        self.turnOn.clicked.connect(transm.turnOn)
        self.modelOff.clicked.connect(transm.turnOff)
        self.dump.clicked.connect(transm.dump)
        self.cooling.clicked.connect(transm.cool)

        #self.cslider.sliderReleased.connect(lambda: citty())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reactor"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Реактор 2 OUT, <span style=\" vertical-align:super;\">0</span>С</p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Реактор 2 IN, <span style=\" vertical-align:super;\">0</span>С</p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Реактор 1 OUT, <span style=\" vertical-align:super;\">0</span>С</p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Реактор 1 IN, <span style=\" vertical-align:super;\">0</span>С</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Энергия</p></body></html>"))
        self.turnOn.setText(_translate("MainWindow", "Включить модель"))
        self.crash1.setText(_translate("MainWindow", "Тестировать перегрев"))
        self.dump.setText(_translate("MainWindow", "Слив"))
        self.cooling.setText(_translate("MainWindow", "Охлаждение"))
        self.modelOff.setText(_translate("MainWindow", "Выключить модель"))
        self.endGame.setText(_translate("MainWindow", "Завершить игру"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Датчики температуры, <span style=\" vertical-align:super;\">0</span>C</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Насос 4, %</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Насос 3, %</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Насос 2, %</p></body></html>"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Насос 1, %</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Поток 1, л/с</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Поток 2, л/с</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Потребление города, %</p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Насос 6, %</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Насос 5, %</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Реактор 2 внутр., <span style=\" vertical-align:super;\">0</span>С</p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Реактор 1 внутр., <span style=\" vertical-align:super;\">0</span>С</p></body></html>"))


import reactor_res_rc


def runApp():
    global exit
    exit = app.exec_()

def logger():
    with open("log.txt", "a+") as log:
        enrg = ui.energyLcd.value()
        city = ui.cslider.value()*koef
        log.write("{} Enrg: {}, City: {} \n".format(
            datetime.datetime.now(), enrg, city))
    for i in range(0, 30):
        time.sleep(1)
        if exit != 1:
            break


if __name__ == "__main__":
    import sys
    transm = rpi.Transmitter()
    exit = 1
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()

    dataThread = Thread(target=getData, args=())
    dataThread.start()
    runApp()
