# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reactor_master.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from threading import Timer
from PyQt5 import QtCore, QtGui, QtWidgets

import arduino as a

def get_sensor_data():
    num = ui.sensorSelector.value()
    val = a.getSensor(num)
    energy = a.getEnergy()
    ui.energyLcd.display(energy)
    ui.sensorLcd.display(val)
    t = Timer(2, get_sensor_data)
    if exit == 1:
        t.start()
    else:
        sys.exit(exit)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(1025, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 768))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAcceptDrops(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Hurricane_in_glass/controls/design/img/nuke logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-image: url(:/img/img/bg_grey.jpg);")
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.waterpipes = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.waterpipes.setFont(font)
        self.waterpipes.setAutoFillBackground(False)
        self.waterpipes.setStyleSheet("")
        self.waterpipes.setObjectName("waterpipes")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.waterpipes)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Nasos1 = QtWidgets.QWidget(self.waterpipes)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.Nasos1.setFont(font)
        self.Nasos1.setAcceptDrops(False)
        self.Nasos1.setAutoFillBackground(False)
        self.Nasos1.setStyleSheet("border: 2px solid white;")
        self.Nasos1.setObjectName("Nasos1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Nasos1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lcd1 = QtWidgets.QLCDNumber(self.Nasos1)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.lcd1.setFont(font)
        self.lcd1.setAutoFillBackground(False)
        self.lcd1.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd1.setObjectName("lcd1")
        self.verticalLayout_2.addWidget(self.lcd1)
        self.label_1 = QtWidgets.QLabel(self.Nasos1)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.label_1.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_1.setAutoFillBackground(False)
        self.label_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_2.addWidget(self.label_1)
        self.horizontalLayout.addWidget(self.Nasos1)
        self.Nasos2 = QtWidgets.QWidget(self.waterpipes)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.Nasos2.setFont(font)
        self.Nasos2.setAutoFillBackground(False)
        self.Nasos2.setStyleSheet("border: 2px solid white;")
        self.Nasos2.setObjectName("Nasos2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Nasos2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lcd2 = QtWidgets.QLCDNumber(self.Nasos2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.lcd2.setFont(font)
        self.lcd2.setAutoFillBackground(False)
        self.lcd2.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd2.setObjectName("lcd2")
        self.verticalLayout_5.addWidget(self.lcd2)
        self.label_4 = QtWidgets.QLabel(self.Nasos2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.horizontalLayout.addWidget(self.Nasos2)
        self.Nasos3 = QtWidgets.QWidget(self.waterpipes)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.Nasos3.setFont(font)
        self.Nasos3.setAutoFillBackground(False)
        self.Nasos3.setStyleSheet("border: 2px solid white;")
        self.Nasos3.setObjectName("Nasos3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Nasos3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lcd3 = QtWidgets.QLCDNumber(self.Nasos3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.lcd3.setFont(font)
        self.lcd3.setAutoFillBackground(False)
        self.lcd3.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd3.setObjectName("lcd3")
        self.verticalLayout_4.addWidget(self.lcd3)
        self.label_3 = QtWidgets.QLabel(self.Nasos3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout.addWidget(self.Nasos3)
        self.Nasos4 = QtWidgets.QWidget(self.waterpipes)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.Nasos4.setFont(font)
        self.Nasos4.setAutoFillBackground(False)
        self.Nasos4.setStyleSheet("border: 2px solid white;")
        self.Nasos4.setObjectName("Nasos4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Nasos4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lcd4 = QtWidgets.QLCDNumber(self.Nasos4)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.lcd4.setFont(font)
        self.lcd4.setAutoFillBackground(False)
        self.lcd4.setStyleSheet("color: rgb(255, 255, 255);")
        self.lcd4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcd4.setObjectName("lcd4")
        self.verticalLayout_3.addWidget(self.lcd4)
        self.label_2 = QtWidgets.QLabel(self.Nasos4)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(24)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px;")
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout.addWidget(self.Nasos4)
        self.verticalLayout.addWidget(self.waterpipes)
        self.menu2 = QtWidgets.QWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.menu2.setFont(font)
        self.menu2.setAutoFillBackground(False)
        self.menu2.setObjectName("menu2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.menu2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sensors = QtWidgets.QWidget(self.menu2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.sensors.setFont(font)
        self.sensors.setAutoFillBackground(False)
        self.sensors.setStyleSheet("border: 2px solid white;")
        self.sensors.setObjectName("sensors")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.sensors)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sensorLcd = QtWidgets.QLCDNumber(self.sensors)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.sensorLcd.setFont(font)
        self.sensorLcd.setAutoFillBackground(False)
        self.sensorLcd.setStyleSheet("color: rgb(255, 255, 255);")
        self.sensorLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sensorLcd.setObjectName("sensorLcd")
        self.verticalLayout_6.addWidget(self.sensorLcd)
        self.sensorSelector = QtWidgets.QSpinBox(self.sensors)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(24)
        self.sensorSelector.setFont(font)
        self.sensorSelector.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sensorSelector.setAutoFillBackground(False)
        self.sensorSelector.setStyleSheet("color: rgb(203, 203, 203);")
        self.sensorSelector.setMinimum(1)
        self.sensorSelector.setMaximum(16)
        self.sensorSelector.setObjectName("sensorSelector")
        self.verticalLayout_6.addWidget(self.sensorSelector)
        self.label_5 = QtWidgets.QLabel(self.sensors)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255); border: 0px;")
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_2.addWidget(self.sensors)
        self.widget_3 = QtWidgets.QWidget(self.menu2)
        self.widget_3.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.widget_3.setFont(font)
        self.widget_3.setAutoFillBackground(False)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.turnOn = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(14)
        self.turnOn.setFont(font)
        self.turnOn.setStyleSheet("color:white;")
        self.turnOn.setObjectName("turnOn")
        self.verticalLayout_7.addWidget(self.turnOn)
        self.crash1 = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(14)
        self.crash1.setFont(font)
        self.crash1.setAutoFillBackground(False)
        self.crash1.setStyleSheet("color: rgb(255, 255, 255);")
        self.crash1.setObjectName("crash1")
        self.verticalLayout_7.addWidget(self.crash1)
        self.crash2 = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(14)
        self.crash2.setFont(font)
        self.crash2.setAutoFillBackground(False)
        self.crash2.setStyleSheet("color: rgb(255, 255, 255);")
        self.crash2.setObjectName("crash2")
        self.verticalLayout_7.addWidget(self.crash2)
        self.crash3 = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(14)
        self.crash3.setFont(font)
        self.crash3.setAutoFillBackground(False)
        self.crash3.setStyleSheet("color: rgb(255, 255, 255);")
        self.crash3.setObjectName("crash3")
        self.verticalLayout_7.addWidget(self.crash3)
        self.modelOff = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(14)
        self.modelOff.setFont(font)
        self.modelOff.setAutoFillBackground(False)
        self.modelOff.setStyleSheet("color: rgb(255, 255, 255);")
        self.modelOff.setObjectName("modelOff")
        self.verticalLayout_7.addWidget(self.modelOff)
        self.playersOff = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(14)
        self.playersOff.setFont(font)
        self.playersOff.setAutoFillBackground(False)
        self.playersOff.setStyleSheet("color: rgb(255, 255, 255);")
        self.playersOff.setObjectName("playersOff")
        self.verticalLayout_7.addWidget(self.playersOff)
        self.endGame = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(14)
        self.endGame.setFont(font)
        self.endGame.setAutoFillBackground(False)
        self.endGame.setStyleSheet("color: rgb(255, 255, 255);")
        self.endGame.setObjectName("endGame")
        self.verticalLayout_7.addWidget(self.endGame)
        self.modelOff.raise_()
        self.endGame.raise_()
        self.playersOff.raise_()
        self.crash1.raise_()
        self.crash2.raise_()
        self.crash3.raise_()
        self.turnOn.raise_()
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.menu2)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.widget_4.setFont(font)
        self.widget_4.setAutoFillBackground(False)
        self.widget_4.setStyleSheet("border: 2px solid white;")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.energyLcd = QtWidgets.QLCDNumber(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        self.energyLcd.setFont(font)
        self.energyLcd.setAutoFillBackground(False)
        self.energyLcd.setStyleSheet("color: rgb(255, 255, 255);")
        self.energyLcd.setFrameShadow(QtWidgets.QFrame.Plain)
        self.energyLcd.setObjectName("energyLcd")
        self.verticalLayout_8.addWidget(self.energyLcd)
        self.label_6 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(24)
        self.label_6.setFont(font)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255); border: 0;")
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.verticalLayout.addWidget(self.menu2)
        MainWindow.setCentralWidget(self.centralwidget)

        # Transclucent text

        def set_transclucent(widget):
            widget.setWindowFlags(QtCore.Qt.FramelessWindowHint)
            widget.setAttribute(QtCore.Qt.WA_TranslucentBackground)

        for i in range(1, 7):
            eval("set_transclucent(self.label_{})".format(i))

        # Button actions

        self.turnOn.clicked.connect(a.turnOn)
        self.modelOff.clicked.connect(a.turnOff)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Reactor"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Насос 1, %</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Насос 2, %</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Насос 3, %</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Насос 4, %</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Датчики, <span style=\" vertical-align:super;\">0</span>C</p></body></html>"))
        self.turnOn.setText(_translate("MainWindow", "Включить модель"))
        self.crash1.setText(_translate("MainWindow", "Поломка 1"))
        self.crash2.setText(_translate("MainWindow", "Поломка 2"))
        self.crash3.setText(_translate("MainWindow", "Поломка N"))
        self.modelOff.setText(_translate("MainWindow", "Выключить модель"))
        self.playersOff.setText(_translate("MainWindow", "Выключить пульт игроков"))
        self.endGame.setText(_translate("MainWindow", "Завершить игру"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Энергия</p></body></html>"))

import reactor_res_rc

if __name__ == "__main__":
    import sys
    exit = 1
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    get_sensor_data()
    exit = app.exec_()

